<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <DebugType>portable</DebugType>
    <Version>10.11.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Authors>Clyde89; LinFor; skrashevich</Authors>
    <Company>Clyde89; LinFor; skrashevich</Company>
    <Product>КиноПоиск</Product>
    <Description>Русскоязычный поставщик метаданных КиноПоиска для Jellyfin.</Description>
    <RepositoryUrl>https://github.com/Clyde89/jellyfin-plugin-kinopoisk</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/Clyde89/jellyfin-plugin-kinopoisk</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Data" Version="10.11.11" />
    <PackageReference Include="Jellyfin.Controller" Version="10.11.11" />
    <PackageReference Include="Jellyfin.Common" Version="10.11.11" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KinopoiskUnofficialInfo.ApiClient\KinopoiskUnofficialInfo.ApiClient.csproj" />
  </ItemGroup>

</Project>
